### ISSUE TITLE
Service following enhancements

### ISSUE THREAD

**Issue by coinchon** [ebu/radiodns-manager#70]
Some enhancements for the service following section:
1) add a dropdown list for the MIME TYPE with some proposals of MIME TYPES (audio/mpeg , audio/aac,..)
2) add a "channel name" for the streaming URL
3) when a channel has been added in service following, the page return to the first station in the list rather than the station that is being worked on.
4) add a tick box for each channel with a global "turn on/off" button rather than for each individual channel

**Comment by mhabegger** [comment]
@coinchon Add Streaming services using the regular channel management.
Report if you see any issues.



On Jun 1, 2015, at 15:09, coinchon <notifications@github.com<mailto:notifications@github.com>> wrote:


Some enhancements for the service following section:
1) add a dropdown list for the MIME TYPE with some proposals of MIME TYPES (audio/mpeg , audio/aac,..)
2) add a "channel name" for the streaming URL
3) when a channel has been added in service following, the page return to the first station in the list rather than the station that is being worked on.
4) add a tick box for each channel with a global "turn on/off" button rather than for each individual channel

-

**Comment by coinchon** [comment]
this a good start, however there are still issues. The URL is then wrong in the SI XML, for example: http://mp3.live.tv-radio.com/fip/all/fiphautdebit.mp3 transforms into http://frsrf.epg.radio.ebu.io/radiodns/epg/XSI.xml

**Comment by mhabegger** [comment]
This is corrected. in latest release except for 4). Please check.

**Comment by coinchon** [comment]
Syntax looks correct, need to test if service following works on a Samsung phone.

**Comment by mhabegger** [comment]
@coinchon Please test again with Samsung and close issue.
